In [1]:
import pandas as pd

In [15]:
#Extracting tables from websites
stats=pd.read_html("https://en.wikipedia.org/wiki/Suresh_Raina")
stats[1]

             Competition   Test    ODI   T20I     FC
0                Matches     18    226     78    109
1            Runs scored    768   5615   1605   6871
2        Batting average  26.48  35.31  29.18  42.15
3               100s/50s    1/7   5/36    1/5  14/45
4              Top score    120   116*    101   204*
5           Balls bowled   1041   2126    349   3457
6                Wickets     13     36     13     41
7        Bowling average  46.38  50.30  34.00  41.97
8   5 wickets in innings      0      0      0      0
9    10 wickets in match      0      0      0      0
10          Best bowling    2/1   3/34    2/6   3/31
11     Catches/stumpings   23/–  102/–   42/–  118/–

In [24]:
#Extracting tables from .csv files
csv=pd.read_csv("https://stats.govt.nz/assets/Uploads/Annual-enterprise-survey/Annual-enterprise-survey-2021-financial-year-provisional/Download-data/annual-enterprise-survey-2021-financial-year-provisional-csv.csv")
csv.rename(columns={'Industry_aggregation_NZSIOC':'Col1','Industry_code_NZSIOC':'Col 3'},inplace=True)
csv

,Year,Col1,Col 3,Industry_name_NZSIOC,Units,Variable_code,Variable_name,Variable_category,Value,Industry_code_ANZSIC06
0,2021,Level 1,99999,All industries,Dollars (millions),H01,Total income,Financial performance,"757,504",ANZSIC06 divisions A-S (excluding classes K633...
1,2021,Level 1,99999,All industries,Dollars (millions),H04,"Sales, government funding, grants and subsidies",Financial performance,"674,890",ANZSIC06 divisions A-S (excluding classes K633...
2,2021,Level 1,99999,All industries,Dollars (millions),H05,"Interest, dividends and donations",Financial performance,"49,593",ANZSIC06 divisions A-S (excluding classes K633...
3,2021,Level 1,99999,All industries,Dollars (millions),H07,Non-operating income,Financial performance,"33,020",ANZSIC06 divisions A-S (excluding classes K633...
4,2021,Level 1,99999,All industries,Dollars (millions),H08,Total expenditure,Financial performance,"654,404",ANZSIC06 divisions A-S (excluding classes K633...
...,...,...,...,...,...,...,...,...,...,...
41710,2013,Level 3,ZZ11,Food product manufacturing,Percentage,H37,Quick ratio,Financial ratios,52,"ANZSIC06 groups C111, C112, C113, C114, C115, ..."
41711,2013,Level 3,ZZ11,Food product manufacturing,Percentage,H38,Margin on sales of goods for resale,Financial ratios,40,"ANZSIC06 groups C111, C112, C113, C114, C115, ..."
41712,2013,Level 3,ZZ11,Food product manufacturing,Percentage,H39,Return on equity,Financial ratios,12,"ANZSIC06 groups C111, C112, C113, C114, C115, ..."
41713,2013,Level 3,ZZ11,Food product manufacturing,Percentage,H40,Return on total assets,Financial ratios,5,"ANZSIC06 groups C111, C112, C113, C114, C115, ..."
41714,2013,Level 3,ZZ11,Food product manufacturing,Percentage,H41,Liabilities structure,Financial ratios,46,"ANZSIC06 groups C111, C112, C113, C114, C115, ..."

In [ ]:
#Extracting tables from .pdf files using camelot-py library
pdf=pd.read_